stages:
  - common-style
  - common-quality
  - common-test
  - package

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
  DOCKER_DRIVER: overlay2
  CODESTYLE_VERSION: "6.4.20.0"
  DEFAULT_SW_VERSION: "v6.2.0"
  PLUGIN_NAME: 'UnzerPayment6'
  COMPOSER_HOME: '/var/www/html/.composer'
  COMPOSER_COMMAND: "/var/www/html/composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader"

include:
  - project: 'kellerkinder/pipeline-common'
    file:
      - '/plugin/codestyle.yml'
      - '/plugin/phpstan/k10r/sw-64.yml'
      - '/plugin/phpstan/k10r/sw-65.yml'
      - '/plugin/phpstan/sw/sw-64.yml'
      - '/plugin/phpstan/sw/sw-65.yml'
      - '/plugin/install/sw-64.yml'
      - '/plugin/install/sw-65.yml'

build-65:
    stage: package
    image:
        name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.5.0
        entrypoint: [""]
    before_script:
        - echo ""
    only:
        - tags
        - master
        - /^integration.*$/
        - /^fix.*$/
    except:
        variables: [ $DISABLE_PACKAGE == "1" ]
    script:
        - start-mysql
        - ln -s "$(pwd)" "/plugins/${CI_PROJECT_NAME}"
        - jq '.version = .version + "65"' /plugins/${CI_PROJECT_NAME}/composer.json > /plugins/${CI_PROJECT_NAME}/composer.tmp && mv /plugins/${CI_PROJECT_NAME}/composer.tmp /plugins/${CI_PROJECT_NAME}/composer.json
        - sed '1 s_$_65_' /plugins/${CI_PROJECT_NAME}/CHANGELOG_en-GB.md > /plugins/${CI_PROJECT_NAME}/CHANGELOG_en-GB.tmp && mv /plugins/${CI_PROJECT_NAME}/CHANGELOG_en-GB.tmp /plugins/${CI_PROJECT_NAME}/CHANGELOG_en-GB.md
        - sed '1 s_$_65_' /plugins/${CI_PROJECT_NAME}/CHANGELOG_de-DE.md > /plugins/${CI_PROJECT_NAME}/CHANGELOG_de-DE.tmp && mv /plugins/${CI_PROJECT_NAME}/CHANGELOG_de-DE.tmp /plugins/${CI_PROJECT_NAME}/CHANGELOG_de-DE.md
        - plugin-uploader ext:prepare "/plugins/${CI_PROJECT_NAME}"
        - rm -rf $( cat .sw-zip-blocklist ) && rm -rf .sw-zip-blocklist
        - pack-plugin ${CI_PROJECT_NAME}
        - plugin-uploader ext:validate "$(realpath "$(find . -type f -name "*.zip" -print0 -maxdepth 1)")"
    artifacts:
        paths:
            - "*.zip"
        expire_in: 1 week