stages:
    - common-style
    - common-quality
    - common-test
    - common-package

cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
    DOCKER_DRIVER: overlay2
    CODESTYLE_VERSION: "6.4.20.0"
    DEFAULT_SW_VERSION: "v6.2.0"
    PLUGIN_NAME: 'UnzerPayment6'
    DISABLE_PHPUNIT: '1'
    COMPOSER_COMMAND: "/var/www/html/composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader"

include:
  - project: 'kellerkinder/pipeline-common'
    ref: feature/INT-1279
    file: 
        - '/plugin/codestyle.yml'
        - '/plugin/install/sw-63.yml'
        - '/plugin/install/sw-64.yml'
        - '/plugin/install/sw-65.yml'
        - '/plugin/phpstan/k10r/sw-63.yml'
        - '/plugin/phpstan/k10r/sw-64.yml'
        - '/plugin/phpstan/sw/sw-63.yml'
        - '/plugin/phpstan/sw/sw-64.yml'
        - '/plugin/phpunit/sw-63.yml'
        - '/plugin/phpunit/sw-64.yml'
        - '/plugin/build-package.yml'
