stages:
    - setup
    - test
    - package

variables:
    MYSQL_ROOT_PASSWORD: shopware
    MYSQL_ROOT_HOST: '%'
    MYSQL_DATABASE: shopware
    MYSQL_USER: shopware
    MYSQL_PASSWORD: shopware
    PLUGIN_NAME: UnzerPayment6
    SHOPWARE_VERSION: "v6.2.0" # Tag

cache:
    key: "$PLUGIN_NAME-$CI_COMMIT_REF_SLUG"

composer:
    stage: setup
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    script:
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader
    artifacts:
        paths:
            - vendor/
        expire_in: 1 days
        when: always
    cache:
        paths:
            - vendor/

phpstan:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    dependencies:
        - composer
    script:
        - git clone -b ${SHOPWARE_VERSION} https://github.com/shopware/development "${CI_PROJECT_DIR}/opt/shopware"
        - rm -rf "${CI_PROJECT_DIR}/opt/shopware/platform"
        - git clone -b ${SHOPWARE_VERSION} https://github.com/shopware/platform "${CI_PROJECT_DIR}/opt/shopware/platform"
        - mv ${CI_PROJECT_DIR}/opt /tmp/opt
        - cp -r ${CI_PROJECT_DIR} /tmp/opt/shopware/custom/plugins/${PLUGIN_NAME}
        - mv /tmp/opt ${CI_PROJECT_DIR}/opt
        - cd ${CI_PROJECT_DIR}/opt/shopware && composer install --no-interaction --optimize-autoloader --no-suggest --no-scripts
        - cd ${CI_PROJECT_DIR}/opt/shopware && composer dump-autoload -d custom/plugins/${PLUGIN_NAME}
        - cd ${CI_PROJECT_DIR}/opt/shopware/custom/plugins/${PLUGIN_NAME} && vendor/bin/phpstan analyse -c phpstan.neon --autoload-file=${CI_PROJECT_DIR}/opt/shopware/vendor/autoload.php src

codestyle:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    dependencies:
        - composer
    script:
        - vendor/bin/php-cs-fixer fix -v --dry-run
    cache:
        key: global
        paths:
            - .php_cs.cache

package:
    image: kellerkinder/shopware-package-plugin:latest
    stage: package
    only:
        - tags
        - master
        - integration*
    services:
        - mysql:5.7
    script:
        - mkdir /tmp/opt
        - git clone -b ${SHOPWARE_VERSION} --depth 1 https://github.com/shopware/production /tmp/opt/shopware
        - cp -r ${CI_PROJECT_DIR} /tmp/opt/shopware/custom/plugins/${CI_PROJECT_NAME}
        - cd /tmp/opt/shopware && composer install --no-interaction -o
        - cd /tmp/opt/shopware && php bin/console system:setup --database-url=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE} --generate-jwt-keys -nq
        - cd /tmp/opt/shopware && php bin/console system:install -fnq --create-database
        - cd /tmp/opt/shopware && php bin/console plugin:refresh -nq && php bin/console plugin:install --activate -c ${CI_PROJECT_NAME} -nq
        - cd /tmp/opt/shopware && bin/build-js.sh
        - cd /tmp/opt/shopware && php bin/console theme:compile -nq
        - rsync -r /tmp/opt/shopware/custom/plugins/${CI_PROJECT_NAME}/ ${CI_PROJECT_DIR}/
        - cd ${CI_PROJECT_DIR} && git add -f .
        - package-plugin
    artifacts:
        paths:
            - ${CI_PROJECT_NAME}.zip

