stages:
    - setup
    - test
    - package

cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
    MYSQL_ROOT_PASSWORD: shopware
    MYSQL_ROOT_HOST: '%'
    MYSQL_DATABASE: shopware
    MYSQL_USER: shopware
    MYSQL_PASSWORD: shopware
    SHOPWARE_VERSION: "v6.2.0" # Tag
    COMPOSER_COMMAND: "composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader"

shopware_redeem:
    stage: setup
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    script:
        - mkdir -p /tmp/opt
        - git clone -b ${SHOPWARE_VERSION} https://github.com/shopware/development "/tmp/opt/shopware"
        - cd /tmp/opt/shopware && ${COMPOSER_COMMAND}
        - cp -r ${CI_PROJECT_DIR} /tmp/opt/shopware/custom/plugins/${CI_PROJECT_NAME} && cd /tmp/opt/shopware/custom/plugins/${CI_PROJECT_NAME} && ${COMPOSER_COMMAND}
        - cd /tmp/opt/shopware && composer dump-autoload -d custom/plugins/${CI_PROJECT_NAME}
        - cp -r /tmp/opt/shopware ${CI_PROJECT_DIR}/sw_dir
    artifacts:
        paths:
            - "sw_dir"
        expire_in: 1 days
        when: always

codestyle:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    needs:
        - job: shopware_redeem
          artifacts: true
    script:
        - cd ${CI_PROJECT_DIR}/sw_dir/custom/plugins/${CI_PROJECT_NAME} && vendor/bin/php-cs-fixer fix -v --dry-run
    cache:
        key: global
        paths:
            - .php_cs.cache

k10r-phpstan:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    needs:
        - job: shopware_redeem
          artifacts: true
    script:
        - cd ${CI_PROJECT_DIR}/sw_dir/custom/plugins/${CI_PROJECT_NAME} && vendor/bin/phpstan analyse -c phpstan.neon src tests -a vendor/autoload.php -a ../../../vendor/autoload.php

sw-phpstan:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.2"
    needs:
        - job: shopware_redeem
          artifacts: true
    before_script:
        - cd /tmp && git clone https://github.com/shopwareLabs/store-plugin-codereview.git
        - cp -r /tmp/store-plugin-codereview/configs/phpstan/phpstan.neon.sw6 ${CI_PROJECT_DIR}/sw_dir/custom/plugins/${CI_PROJECT_NAME}/phpstan_sw.neon
    script:
        - cd ${CI_PROJECT_DIR}/sw_dir/custom/plugins/${CI_PROJECT_NAME} && vendor/bin/phpstan analyse -c phpstan_sw.neon -a vendor/autoload.php -a ../../../vendor/autoload.php src tests

package:
    image: kellerkinder/shopware-package-plugin:latest
    stage: package
    only:
        - tags
        - master
        - /^integration.*$/
        - /^fix.*$/
    services:
        - mysql:5.7
    script:
        - mkdir /tmp/opt
        - git clone -b ${SHOPWARE_VERSION} --depth 1 https://github.com/shopware/production /tmp/opt/shopware
        - cp -r ${CI_PROJECT_DIR} /tmp/opt/shopware/custom/plugins/${CI_PROJECT_NAME}
        - cd /tmp/opt/shopware && ${COMPOSER_COMMAND}
        - cd /tmp/opt/shopware/custom/plugins/${CI_PROJECT_NAME} && ${COMPOSER_COMMAND}
        - cd /tmp/opt/shopware && php bin/console system:setup --database-url=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE} --generate-jwt-keys -nq
        - cd /tmp/opt/shopware && php bin/console system:install -fnq --create-database
        - cd /tmp/opt/shopware && php bin/console plugin:refresh -nq && php bin/console plugin:install --activate -c ${CI_PROJECT_NAME} -nq
        - cd /tmp/opt/shopware && bin/build-js.sh
        - cd /tmp/opt/shopware && php bin/console theme:compile -nq
        - rsync -r /tmp/opt/shopware/custom/plugins/${CI_PROJECT_NAME}/ ${CI_PROJECT_DIR}/
        - cd ${CI_PROJECT_DIR} && git add -f .
        - package-plugin
        - unzip -vl ${CI_PROJECT_NAME}.zip
    artifacts:
        paths:
            - ${CI_PROJECT_NAME}.zip
