stages:
    - style
    - quality
    - test
    - package
    - validate

cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
    DOCKER_DRIVER: overlay2
    BASE_SW_VERSION: '6.3.4.0'
    PLUGIN_NAME: 'UnzerPayment6'
    DISABLE_PHPUNIT: '1'
    COMPOSER_COMMAND: "/var/www/html/composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader"
    COMPOSER_HOME: '/var/www/html/.composer'

codestyle:
    stage: style
    image: "dockware/play:${BASE_SW_VERSION}"
    needs: [ ]
    except:
        variables: [ $DISABLE_PHP_CS == "1" ]
    before_script:
        - curl https://getcomposer.org/download/1.10.19/composer.phar -o /var/www/html/composer
        - chmod +x /var/www/html/composer
        - if [ $SW_VERSION == '6.4.0.0' ] || [ $SW_VERSION == '6.4.20.0' ]; then /var/www/html/composer self-update 2.4.4; else /var/www/html/composer global require hirak/prestissimo; fi
        - ${COMPOSER_COMMAND}
        - cp -r ${CI_PROJECT_DIR} /var/www/html/custom/plugins/${PLUGIN_NAME}
    script:
        - cd /var/www/html/custom/plugins/${PLUGIN_NAME} && vendor/bin/php-cs-fixer fix -v --dry-run
    cache:
        key: global
        paths:
            - .php_cs.cache
            - vendor

k10r-phpstan:
    stage: quality
    image: "dockware/play:${SW_VERSION}"
    parallel:
        matrix:
            -   PHP_VERSION: [ "7.2", "7.3", "7.4", "8.0", "8.1" ]
                SW_VERSION: [ "6.3.4.0", "6.3.5.0" ]
            -   PHP_VERSION: [ "7.4", "8.0", "8.1" ]
                SW_VERSION: [ "6.4.0.0", "6.4.20.0" ]
    needs: [ ]
    except:
        variables: [ $DISABLE_PHPSTAN_K10R == "1" ]
    before_script:
        - curl https://getcomposer.org/download/1.10.19/composer.phar -o /var/www/html/composer
        - chmod +x /var/www/html/composer
        - if [ $SW_VERSION == '6.4.0.0' ] || [ $SW_VERSION == '6.4.20.0' ]; then /var/www/html/composer self-update 2.4.4; else /var/www/html/composer global require hirak/prestissimo; fi
        - ${COMPOSER_COMMAND}
        - cp -r ${CI_PROJECT_DIR} /var/www/html/custom/plugins/${PLUGIN_NAME}
    script:
        - cd /var/www/html/custom/plugins/${PLUGIN_NAME} && vendor/bin/phpstan analyse -c phpstan.neon src tests
    cache:
        key: global
        paths:
            - vendor

sw-phpstan:
    stage: quality
    image: "dockware/play:${SW_VERSION}"
    parallel:
        matrix:
            - PHP_VERSION: [ "7.2", "7.3", "7.4", "8.0", "8.1" ]
              SW_VERSION: [ "6.3.4.0", "6.3.5.0" ]
            - PHP_VERSION: [ "7.4", "8.0", "8.1" ]
              SW_VERSION: [ "6.4.0.0", "6.4.20.0" ]
    needs: [ ]
    except:
        variables: [ $DISABLE_PHPSTAN_SW == "1" ]
    before_script:
        - curl https://getcomposer.org/download/1.10.19/composer.phar -o /var/www/html/composer
        - chmod +x /var/www/html/composer
        - if [ $SW_VERSION == '6.4.0.0' ] || [ $SW_VERSION == '6.4.20.0' ]; then /var/www/html/composer self-update 2.4.4; else /var/www/html/composer global require hirak/prestissimo; fi
        - ${COMPOSER_COMMAND}
        - cp -r ${CI_PROJECT_DIR} /var/www/html/custom/plugins/${PLUGIN_NAME}
        - cd /tmp && git clone https://github.com/shopwareLabs/store-plugin-codereview.git
        - cp -r /tmp/store-plugin-codereview/configs/phpstan/phpstan.neon.sw6 /var/www/html/custom/plugins/${PLUGIN_NAME}/phpstan_sw.neon
    script:
        - cd /var/www/html/custom/plugins/${PLUGIN_NAME} && vendor/bin/phpstan analyse -c phpstan_sw.neon -a vendor/autoload.php -a ../../../vendor/autoload.php src tests
    cache:
        key: global
        paths:
            - vendor

phpunit:
    stage: test
    image: "dockware/play:${SW_VERSION}"
    parallel:
        matrix:
            - PHP_VERSION: [ "7.2", "7.3", "7.4", "8.0", "8.1" ]
              SW_VERSION: [ "6.3.4.0", "6.3.5.0" ]
            - PHP_VERSION: [ "7.4", "8.0", "8.1" ]
              SW_VERSION: [ "6.4.0.0", "6.4.20.0" ]
    needs: [ ]
    except:
        variables: [ $DISABLE_PHPUNIT == "1" ]
    before_script:
        - curl https://getcomposer.org/download/1.10.19/composer.phar -o /var/www/html/composer
        - chmod +x /var/www/html/composer
        - if [ $SW_VERSION == '6.4.0.0' ] || [ $SW_VERSION == '6.4.20.0' ]; then /var/www/html/composer self-update 2.4.4; else /var/www/html/composer global require hirak/prestissimo; fi
        - ${COMPOSER_COMMAND}
        - cp -r ${CI_PROJECT_DIR} /var/www/html/custom/plugins/${PLUGIN_NAME}
        - sudo rm -rf /var/run/mysqld/mysqld.sock.lock
        - sudo chown -R mysql:mysql /var/lib/mysql /var/run/mysqld
        - sudo service mysql start
        - cd /var/www/html/ && rm -rf vendor && ${COMPOSER_COMMAND} --no-scripts
    script:
        - cd /var/www/html/ && php bin/console plugin:refresh -nq && php bin/console plugin:install --activate -c ${PLUGIN_NAME} -nq
        - cd /var/www/html/ && /var/www/html/composer dump-autoload -d custom/plugins/${PLUGIN_NAME}
        - cd /var/www/html/ && php -d pcov.enabled=1 -d pcov.directory=/var/www/html/
            vendor/bin/phpunit
            --configuration custom/plugins/${PLUGIN_NAME}/phpunit.xml.dist
    cache:
        key: global
        paths:
            - vendor

package:
    image:
        name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.17
        entrypoint: [""]
    stage: package
    only:
        - tags
        - master
        - develop
        - /^integration.*$/
        - /^fix.*$/
    except:
        variables: [ $DISABLE_PACKAGE == "1" ]
    script:
        - start-mysql
        - ln -s "$(pwd)" "/plugins/${PLUGIN_NAME}"
        - plugin-uploader ext:prepare "/plugins/${PLUGIN_NAME}"
        - rm -rf $( cat .sw-zip-blocklist ) && rm -rf .sw-zip-blocklist
        - pack-plugin ${PLUGIN_NAME}
    artifacts:
        paths:
            - "*.zip"

shopware-validate:
    image:
        name: friendsofshopware/plugin-uploader:0.3.19
        entrypoint: [ "/bin/sh", "-c" ]
    stage: validate
    needs:
        - package
    only:
        - tags
        - master
        - /^integration.*$/
        - /^fix.*$/
    except:
        variables: [ $DISABLE_VALIDATION == "1" ]
    script:
        - php /app/bin/pluginupload ext:validate ${PLUGIN_NAME}.zip
