stages:
  - common-style
  - common-quality
  - common-test
  - common-package

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

variables:
  DOCKER_DRIVER: overlay2
  CODESTYLE_VERSION: "6.4.20.0"
  DEFAULT_SW_VERSION: "v6.2.0"
  PLUGIN_NAME: 'UnzerPayment6'
  COMPOSER_HOME: '/var/www/html/.composer'
  COMPOSER_COMMAND: "/var/www/html/composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader"

include:
  - project: 'kellerkinder/pipeline-common'
    ref: feature/INT-1279
    file:
      - '/plugin/codestyle.yml'
      - '/plugin/phpstan/k10r/sw-63.yml'
      - '/plugin/phpstan/k10r/sw-64.yml'
      - '/plugin/phpstan/k10r/sw-65.yml'
      - '/plugin/phpstan/sw/sw-63.yml'
      - '/plugin/phpstan/sw/sw-64.yml'
      - '/plugin/phpstan/sw/sw-65.yml'
      - '/plugin/install/sw-63.yml'
      - '/plugin/install/sw-64.yml'
      - '/plugin/install/sw-65.yml'
      - '/plugin/build-package.yml'

k10r-phpstan-65:
  parallel:
    matrix:
      -   PHP_VERSION: [ "8.1" ]
          SW_VERSION: [ "6.5.0.0" ]

sw-phpstan-65:
  parallel:
    matrix:
      -   PHP_VERSION: [ "8.1" ]
          SW_VERSION: [ "6.5.0.0" ]
  script:
    - cd /var/www/html
    - /var/www/html/composer config --no-plugins allow-plugins.bamarni/composer-bin-plugin true
    - /var/www/html/composer require --dev --no-interaction code-quality bamarni/composer-bin-plugin
    - "jq '.extra += {\"bamarni-bin\": {\"bin-links\": false, \"forward-command\": true}}' composer.json > composer.tmp && mv composer.tmp composer.json"
    - ${COMPOSER_COMMAND}
    - vendor-bin/phpstan/vendor/bin/phpstan analyse -c phpstan_sw.neon -a vendor/autoload.php -a ../../../vendor/autoload.php src tests

install-63:
  parallel:
    matrix:
      -   PHP_VERSION: [ "7.2", "7.3" ]
          SW_VERSION: [ "6.3.4.0", "6.3.5.0" ]

install-65:
  parallel:
    matrix:
      -   PHP_VERSION: [ "8.1" ]
          SW_VERSION: [ "6.5.0.0" ]
